### ISSUE TITLE
EG indexer returning an error

### ISSUE THREAD

**Issue by sandbergja** [lbcclib/findit#392]
```
indexer_1  | 2020-11-25T07:04:11+00:00 [FATAL] 1685 : Traject::CommandLine: Unexpected exception, terminating execution:     Exception: NoMethodError: undefined method `pack' for nil:NilClass
indexer_1  |     /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:364:in `block in decode'
indexer_1  | 
indexer_1  | bundler: failed to load command: traject (/usr/local/bundle/bin/traject)
indexer_1  | NoMethodError: undefined method `pack' for nil:NilClass
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:364:in `block in decode'
indexer_1  |   org/jruby/RubyInteger.java:208:in `upto'
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:339:in `decode'
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:283:in `decode'
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:233:in `block in each'
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:273:in `each_raw'
indexer_1  |   /usr/local/bundle/gems/marc-1.0.4/lib/marc/reader.rb:232:in `each'
indexer_1  |   /usr/local/bundle/gems/traject-3.4.0/lib/traject/marc_reader.rb:87:in `each'
indexer_1  |   /usr/local/bundle/gems/traject-3.4.0/lib/traject/indexer.rb:553:in `block in process'
indexer_1  |   org/jruby/RubyArray.java:1809:in `each'
indexer_1  |   /usr/local/bundle/gems/traject-3.4.0/lib/traject/indexer.rb:546:in `process'
indexer_1  |   /usr/local/bundle/gems/traject-3.4.0/lib/traject/command_line.rb:73:in `execute'
indexer_1  |   /usr/local/bundle/gems/traject-3.4.0/bin/traject:14:in `<main>'
indexer_1  |   org/jruby/RubyKernel.java:1009:in `load'
indexer_1  |   /usr/local/bundle/bin/traject:23:in `<main>'
indexer_1  |   org/jruby/RubyKernel.java:1009:in `load'
```

**Comment by sandbergja** [comment]
Somewhere after record with tcn 470_000
